---
- name: restart telegraf
  service:
    name: telegraf
    state: restarted
  become: true

- name: restart telegraf windows
  win_service:
    name: Telegraf
    start_mode: auto
    state: restarted