kind: pipeline
type: docker
name: default

steps:
  - name: pull
    image: ubuntu
    volumes:
      - name: host-ansible
        path: /tmp/ansible
    commands:
      - rm -R /tmp/ansible/playbooks/* /tmp/ansible/roles/* -f
      - cp -R /drone/src/* /tmp/ansible/
      - chown -R root:1565204120 /tmp/ansible
      - chmod -R 771 /tmp/ansible

volumes:
- name: host-ansible
  host:
    path: /opt/automation/ansible