kind: pipeline
type: docker
name: default

steps:
  - name: pull
    image: ubuntu
    volumes:
      - name: host-ansible
        path: /tmp/ansible
    commands:
      - cp -R /drone/src/* /tmp/ansible/
      
volumes:
- name: host-ansible
  host:
    path: /etc/ansible