---
- name: Enable bridged traffic
  shell: |
    sudo modprobe br_netfilter
    sudo cat << EOF | sudo tee /etc/modules-load.d/containerd.conf
    overlay
    br_netfilter
    EOF
    sudo cat << EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF
    sudo modprobe overlay
    sudo modprobe br_netfilter
    sudo sysctl --system
  become: true
  when: enable_bridged_traffic | default(false)

