---
- name: Clone VM from template (dhcp)
  vmware_guest:
    template: "{{ template }}"
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    datastore: "{{ datastore }}"
    folder: "/{{ datacenter_name }}/vm/{{ default_folder }}"
    name: "{{ vm_name }}"
    hardware:
      num_cpus: "{{ num_cpus }}"
      memory_mb: "{{ memory_mb }}"
      hotadd_cpu: yes
      hotadd_memory: yes
      hotremove_cpu: yes
    disk:
      - size_gb: "{{ disk_size }}"
    networks:
    - name: "{{ vswitch  }}"
      connected: yes
      device_type: vmxnet3
    customization:
      hostname: "{{ vm_name }}"
    state: poweredon
    wait_for_ip_address: yes