---
- name: Include clone vm from template task
  include_tasks: "clone-vm-from-template.yml"
  when: task == "clone-vm-from-template"

- name: Add group to object
  vmware_object_role_permission:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_usr }}"
    password: "{{ vcenter_pwd }}"
    validate_certs: no
    role: "{{ vcenter_role }}"
    group: "{{ vcenter_group }}"
    object_name: "{{ vcenter_object_name }}"
    object_type: "{{ vcenter_object_type }}"
    state: present
    recursive: "{{ vcenter_propagate }}"
  when: task == "add-group-permission"

- name: Create VM folder
  vcenter_folder:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_usr }}"
    password: "{{ vcenter_pwd }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    folder_name: "{{ vcenter_folder_name }}"
    folder_type: vm
    state: present
  when: task == "create-vm-folder"

- name: Create recourse pool
  vmware_resource_pool:
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_usr }}"
    password: "{{ vcenter_pwd }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    resource_pool: "{{ vcenter_resource_pool_name }}"
    cpu_limit: "{{ vcenter_cpu_limit }}"
    mem_limit: "{{ vcenter_mem_limit }}"
    state: present
  when: task == "create-resource-pool"