---
- name: Update the system
  dnf:
    name: '*'
    state: latest
  when: update | default(false)

- name: Check needs-restarting
  shell: dnf needs-restarting -r ; echo $?
  args:
    warn: false
  register: restart_required_command
  when: allow_restart | default(false)

- name: Check the output of needs-restarting
  set_fact:
    restart_required: "{{ restart_required_command.stdout_lines | last }}"
  when: allow_restart | default(false)

- name: Restart if rquired
  reboot:
  when: allow_restart | default(false)