---
- name: Install AD packages
  dnf:
    name: "{{ ad_packages }}"
    state: present
  tags:
    - ad-packages

- name: Install pexpect
  pip:
    name: pexpect
    executable: pip3
  tags:
    - ad-packages

- name: Setup DNS servers
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - ad-join

- name: Join domain
  expect:
    command: /bin/bash -c "/usr/sbin/realm join "--user={{ ad_usr }}" "--computer-ou={{ ad_ou }}" "--os-name={{ ansible_distribution }}" "--os-version={{ ansible_distribution_version }}" "{{ ad_domain }}""
    responses:
      Password for *: "{{ ad_pwd }}"
  tags:
    - ad-join

- name: Allow login without domain FQDN
  lineinfile:
    backup: yes
    state: present
    dest: /etc/sssd/sssd.conf
    regexp: '^{{ item.search }}'
    line: '{{ item.replace }}'
  with_items:
    - { search: 'use_fully_qualified_names', replace: 'use_fully_qualified_names = False' }
    - { search: 'fallback_homedir', replace: 'fallback_homedir = /home/%u'}
  notify: restart sssd
  tags:
    - ad-join

- name: Restrict login to Linux Admins group
  lineinfile:
    backup: yes
    state: present
    path: /etc/sssd/sssd.conf
    line: 'ldap_access_filter=(memberOf={{ ad_admin_group }})'
    insertafter: EOF
  notify: restart sssd
  tags:
    - ad-join

- name: Create AD Sudoers file
  file:
    path: /etc/sudoers.d/AD
    state: touch
  tags:
    - ad-join

- name: Add Linux Admins to Sudoers
  lineinfile:
    backup: no
    state: present
    path: /etc/sudoers.d/AD
    line: '%Linux\ Admins ALL=(ALL) ALL'
    insertafter: EOF
  tags:
    - ad-join