---
- name: Configure Firewall-cmd for Swarm
  command:
    cmd: firewall-cmd --zone=public --add-service=docker-swarm --permanent
  tags:
    - swarm

- name: Add masquerade to Firewall-cmd
  command:
    cmd: firewall-cmd --add-masquerade --permanent
  tags:
    - swarm