---
- name: Include distribution tasks (Rocky)
  include_tasks: "rocky.yml"
  when: ansible_distribution == "Rocky"
  
- name: Include distribution tasks (Windows)
  include_tasks: "windows.yml"
  when: ansible_os_family == "Windows"