---
- name: "Check single service"
  win_service:
    name: "{{ service }}"
  register: "check_single_service_result"
  failed_when: check_single_service_result is not defined
  when: service is defined

- debug:
    msg: 
      - "{{ check_single_service_result.name }} = {{ check_single_service_result.state }}"
  when: service is defined

- name: "Check multiple services"
  win_service:
    name: "{{ item }}"
  with_items:
    - "{{ services }}"
  register: "check_multiple_services_result"
  failed_when: check_multiple_services_result is not defined
  when: services is defined

- debug:
    msg: "{% set output = [] %}\
        {% for result in check_multiple_services_result.results %}\
          {{ output.append( result.name ~ ' = ' ~ result.state) }}\
        {% endfor %}\
      {{ output }}"
  when: services is defined