---
- name: Add swarm service to firewalld
  firewalld:
    service: docker-swarm
    permanent: yes
    immediate: yes
    state: enabled
  notify: reload firewalld
  when: swarm | default(false)

- name: Add masquerade to firewalld
  firewalld:
    masquerade: enabled
    permanent: yes
    immediate: yes
    state: enabled
  notify: reload firewalld
  when: swarm | default(false)