---
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: disable | default(false)

- name: Add swarm service to firewalld
  firewalld:
    service: docker-swarm
    permanent: yes
    immediate: yes
    state: enabled
  notify: reload firewalld
  when: swarm | default(false)

- name: Add masquerade to firewalld
  firewalld:
    masquerade: enabled
    permanent: yes
    immediate: yes
    state: enabled
  notify: reload firewalld
  when: swarm | default(false)