---
ad_packages:
  - sssd
  - sssd-tools
  - realmd
  - oddjob
  - oddjob-mkhomedir
  - adcli
  - samba-common
  - samba-common-tools
  - krb5-workstation
  - openldap-clients
  - python3-pip

ad_domain: AD.SNOWLAB.XYZ
ad_ou: OU=Linux,OU=Servers,OU=Snowlab,DC=ad,DC=snowlab,DC=xyz
ad_admin_group: CN="Linux Admins",OU=Groups,OU=Snowlab,DC=ad,DC=snowlab,DC=xyz