---
- hosts: all
  remote_user: ansible
  become: true
  
  tasks:
    - name: Include docker role
      import_role:
        name: docker

    - name: Include firewall-cmd role
      import_role:
        name: firewall-cmd