---
- hosts: all
  
  tasks:
    - name: Include telegraf role
      import_role:
        name: telegraf
      vars:
        install: true
        configure: true          

    - name: Include service-status role
      import_role:
        name: service-status
      vars:
        service: telegraf