---
- hosts: all

  vars_files:
    - vars/vault.yml

  tasks:
    - name: Include docker role
      import_role:
        name: docker
      vars:
        install: true
        swarm: true
        allow_restart: true

    - name: Include firewalld role
      import_role:
        name: firewalld
      vars:
        swarm: true

    - name: Include service-status role
      import_role:
        name: service-status
      vars:
        service: docker