---
- hosts: all

  vars_files:
    - vars/vault.yml

  tasks:
    - name: Include telegraf role
      import_role:
        name: docker
      vars:
        install: true

    - name: Include service-status role
      import_role:
        name: service-status