---
- hosts: all

  vars_files:
    - vars/vault.yml

  tasks:
    - name: Include SELinux role
      import_role:
        name: selinux
      vars:
        status: disabled
    
    - name: Include swap role
      import_role:
        name: swap
      vars:
        disable: true

    - name: Include iptables role
      import_role:
        name: iptables
      vars:
        enable_bridged_traffic: true

    - name: Include containerd role
      import_role:
        name: containerd
      vars:
        install: true
        configure: true

    - name: Include Kubernetes role
      import_role:
        name: kubernetes
      vars:
        install: true