---
- name: Add InfluxData repository
  yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
  when: install | default(false)

- name: Install Telegraf
  yum:
    name: telegraf
    state: latest
  when: install | default(false)

- name: Enable Telegraf service
  service:
    name: telegraf
    enabled: yes
  when: install | default(false)
    
- name: Start Telegraf service
  service:
    name: telegraf
    state: started
  when: install | default(false)

- name: Copy config
  copy:
    src: telegraf-linux.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  notify:
    - restart telegraf
  when: configure | default(false)

- meta: flush_handlers