---
- name: Add Docker repo
  command:
    cmd: sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: install | default(false)

- name: Install Containerd
  dnf:
    name: "{{ containerd_packages }}"
  when: install | default(false)

- name: Configure Containerd
  shell: |
    sudo mkdir -p /etc/containerd
    sudo containerd config default | sudo tee /etc/containerd/config.toml
  when: configure | default(false)

- name: Configure Cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '            SystemdCgroup = false'
    line: '            SystemdCgroup = true'
  notify: restart containerd
  when: configure | default(false)

- name: Start and enable containerd
  systemd:
    name: containerd
    state: started
    enabled: true
  when: configure | default(false)